apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: skaffold-project

build:
  local:
    push: false
  artifacts:
    - image: core-service
      context: ./core
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: /app
          - src: "**/*.json"
            dest: /app

    - image: notification-service
      context: ./notification
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: /app
          - src: "**/*.json"
            dest: /app

manifests:
  rawYaml:
    - k8s/core-deployment.yml
    - k8s/notification-deployment.yml
    - k8s/core-service.yml
    - k8s/notification-service.yml
    - k8s/ingress.yml

portForward:
  - resourceType: service
    resourceName: core-service
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: notification-service
    port: 80
    localPort: 4000